image: mcr.microsoft.com/playwright/java:v1.56.0-jammy

stages:
  - test

variables:
  MAVEN_CLI_OPTS: "-B"
  BASE_URL: "https://www.postfinance.ch/ap/ga/ob/html/finance"
  HEADLESS: "true"
  LANGUAGE: "DE"

ui_tests:
  stage: test
  script:
    - echo "BASE_URL = $BASE_URL"
    - echo "HEADLESS = $HEADLESS"
    - echo "LANGUAGE = $LANGUAGE"
    - curl -I "$BASE_URL" || echo "curl failed"

    # 1) Tests laufen lassen, Exit-Code merken
    - |
      set +e
      mvn $MAVEN_CLI_OPTS clean test \
        -Dlang=$LANGUAGE \
        -Dallure.results.directory=target/allure-results
      TEST_EXIT_CODE=$?
      set -e

    # 2) Allure-Report IMMER generieren (auch wenn Tests fehlschlagen)
    - mvn $MAVEN_CLI_OPTS allure:report || true

    # 3) Sicherstellen, dass das Verzeichnis existiert (gegen Warnung)
    - mkdir -p target/site/allure-maven-plugin

    # 4) Job-Exitcode = Test-Exitcode
    - exit $TEST_EXIT_CODE

  artifacts:
    when: always
    expire_in: 14 days
    reports:
      junit:
        - target/surefire-reports/*.xml
    paths:
      - target/surefire-reports/
      - test-output/
      - target/allure-results/
      - target/site/allure-maven-plugin/
#image: mcr.microsoft.com/playwright/java:v1.56.0-jammy
#
#stages:
#  - test
#
#variables:
#  MAVEN_CLI_OPTS: "-B"
#  BASE_URL: "https://www.postfinance.ch/ap/ga/ob/html/finance"
#  HEADLESS: "true"
#  LANGUAGE: "DE"
##  CHECK_WIZARD: "true"
#
#ui_tests:
#  stage: test
#  script:
#    - echo "BASE_URL = $BASE_URL"
#    - echo "HEADLESS = $HEADLESS"
#    - echo "LANGUAGE = $LANGUAGE"
#    - curl -I "$BASE_URL" || echo "curl failed"
#    - mvn $MAVEN_CLI_OPTS clean test -Dsurefire.suiteXmlFiles=testng.xml -Dlang=$LANGUAGE
#
#
#  artifacts:
#    when: always
#    expire_in: 14 days
#    reports:
#      junit:
#        - target/surefire-reports/*.xml
#    paths:
#      - target/surefire-reports/
#      - test-output/