image: mcr.microsoft.com/playwright/java:v1.56.0-jammy

stages:
  - test

variables:
  MAVEN_CLI_OPTS: "-B"
  BASE_URL: "https://www.postfinance.ch/ap/ga/ob/html/finance"
  HEADLESS: "true"
  LANGUAGE: "DE"
#  CHECK_WIZARD: "true"

ui_tests:
  stage: test
  script:
    - echo "BASE_URL = $BASE_URL"
    - echo "HEADLESS = $HEADLESS"
    - echo "LANGUAGE = $LANGUAGE"
    - curl -I "$BASE_URL" || echo "curl failed"
    # 1) Tests ausführen, Allure-Results nach target/allure-results schreiben
    - mvn $MAVEN_CLI_OPTS clean test \
      -Dsurefire.suiteXmlFiles=testng.xml \
      -Dlang=$LANGUAGE \
      -Dallure.results.directory=target/allure-results
    # 2) Allure-Report generieren (HTML unter target/site/allure-maven-plugin)
    - mvn $MAVEN_CLI_OPTS allure:report

  artifacts:
    when: always
    expire_in: 14 days
    reports:
      junit:
        - target/surefire-reports/*.xml
    paths:
      # wie bisher für GitLab Test-Summary
      - target/surefire-reports/
      - test-output/
      # NEU: Allure Ergebnisse (JSON) + HTML-Report
      - target/allure-results/
      - target/site/allure-maven-plugin/
#image: mcr.microsoft.com/playwright/java:v1.56.0-jammy
#
#stages:
#  - test
#
#variables:
#  MAVEN_CLI_OPTS: "-B"
#  BASE_URL: "https://www.postfinance.ch/ap/ga/ob/html/finance"
#  HEADLESS: "true"
#  LANGUAGE: "DE"
##  CHECK_WIZARD: "true"
#
#ui_tests:
#  stage: test
#  script:
#    - echo "BASE_URL = $BASE_URL"
#    - echo "HEADLESS = $HEADLESS"
#    - echo "LANGUAGE = $LANGUAGE"
#    - curl -I "$BASE_URL" || echo "curl failed"
#    - mvn $MAVEN_CLI_OPTS clean test -Dsurefire.suiteXmlFiles=testng.xml -Dlang=$LANGUAGE
#
#
#  artifacts:
#    when: always
#    expire_in: 14 days
#    reports:
#      junit:
#        - target/surefire-reports/*.xml
#    paths:
#      - target/surefire-reports/
#      - test-output/